# preload = ~/.dotfiles/car-with-full-moon-background.jpg
wallpaper {
  monitor = HDMI-A-3
  path = ~/.dotfiles/car-with-full-moon-background.jpg
  fit_mode = cover
}

wallpaper {
  monitor = eDP-1
  path = ~/.dotfiles/car-with-full-moon-background.jpg
  fit_mode = cover
}
