# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule = opacity 0.85 override 0.85 override 0.85 override, match:class kitty

windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = float, title:^(Volume Control)$
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrulev2 = opacity 0.0 override, class:^(xwaylandvideobridge)$
windowrulev2 = noanim, class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus, class:^(xwaylandvideobridge)$
windowrulev2 = maxsize 1 1, class:^(xwaylandvideobridge)$
windowrulev2 = noblur, class:^(xwaylandvideobridge)$
windowrulev2 = nofocus, class:^(xwaylandvideobridge)$
