# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule = opacity 0.85 override 0.85 override 0.85 override, match:class kitty
windowrule = opacity 0.85 override 0.85 override 0.85 override, match:class com.vscodium.codium
windowrule = suppress_event maximize, match:class *
windowrule = float on, match:class ^(blueman-manager)$
# windowrule = match:class ^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0, no_focus on
windowrule = float on, match:title (Volume Control)$
windowrule = opacity 0.0 override, match:class ^(xwaylandvideobridge)$
windowrule = no_anim on, match:class ^(xwaylandvideobridge)$
windowrule = no_initial_focus on, match:class ^(xwaylandvideobridge)$
windowrule = max_size 1 1, match:class ^(xwaylandvideobridge)$
windowrule = no_blur on, match:class ^(xwaylandvideobridge)$
windowrule = no_focus on, match:class ^(xwaylandvideobridge)$
